In [ ]:
import sys
from pathlib import Path

import pandas as pd

In [4]:
data_dir = Path("../../data")

In [10]:
features_df = pd.read_csv(data_dir / "processed" / "mirrors_clusters.csv")
mirrors_ts_df = pd.read_csv(data_dir / "processed" / "filtered_mirrors_ts.csv")

In [11]:
features_df

        article  cluster_final  is_core
0       6718758              4     True
1       6718759              4     True
2       6718760              4     True
3       6718761             11    False
4       6795050              4     True
...         ...            ...      ...
1506  246295120              7     True
1507  246295123              7     True
1508  246300261              8    False
1509  246300263              7     True
1510  246300264              7     True

[1511 rows x 3 columns]

In [12]:
mirrors_ts_df

         article  sales        date
0      151892374      0  2023-03-01
1      151892374      0  2023-04-01
2      151892374      0  2023-05-01
3      151892374      0  2023-06-01
4      151892374      0  2023-07-01
...          ...    ...         ...
22550  177970949     48  2024-12-01
22551  177970950      0  2024-12-01
22552  194818447      0  2024-12-01
22553  239532481      1  2024-12-01
22554  239533051      0  2024-12-01

[22555 rows x 3 columns]